version: '3.1'

services:
  db:
    image: postgres:13.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ocp-request
      POSTGRES_DB: ocp-request
      POSTGRES_PASSWORD: 12345